# : Manager [[[

[mgr]
cwd = { fg = "#e1e2e9" }

# Tab
tab_active = { fg = "#03305f", bg = "#a6c8ff", bold = true }
tab_inactive = { fg = "#d5e3ff", bg = "#001c3b" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#e672ff", bg = "#e672ff" }
marker_cut = { fg = "#f8d8ff", bg = "#f8d8ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#dbbde2", bg = "#dbbde2" }

# Count
count_copied = { fg = "#27132f", bg = "#f8d8ff" }
count_cut = { fg = "#27132f", bg = "#f8d8ff" }
count_selected = { fg = "#03305f", bg = "#dbbde2" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#a6c8ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#03305f", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#a6c8ff", fg = "#03305f", bold = true }
normal_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# Select mode
select_main = { bg = "#bdc7dc", fg = "#273141", bold = true }
select_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# Unset mode
unset_main = { bg = "#dbbde2", fg = "#3e2846", bold = true }
unset_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a6c8ff", bg = "#37393e" }
progress_error = { fg = "#ffb4ab", bg = "#37393e" }

# Permissions
permissions_t = { fg = "#5972a7" }
permissions_w = { fg = "#a153b3" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#dd3fff" }
permissions_s = { fg = "#3c7dff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#a6c8ff" }
active = { fg = "#dbbde2", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#a6c8ff" }
value = { fg = "#e1e2e9" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#a6c8ff", bold = true, bg = "#111318" }
inactive = { fg = "#bdc7dc", bg = "#111318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#a6c8ff", bg = "#03305f" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a6c8ff" }
title = {}
hovered = { fg = "#f8d8ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#37393e" }
cand = { fg = "#a6c8ff" }
rest = { fg = "#03305f" }
desc = { fg = "#e1e2e9" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e1e2e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e1e2e9" }
run = { fg = "#e1e2e9" }
footer = { fg = "#273141", bg = "#bdc7dc" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#dbbde2" }
title_warn = { fg = "#a6c8ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e1e2e9" },
    { name = "*/", fg = "#a6c8ff" },
]

# : ]]]